### ISSUE TITLE
Error when save to a file after encryption

### ISSUE THREAD

**Issue by punishercoder** [punishercoder/r_crypto#10]
This is my error: The content is on the file: acessos.rencrypted
Traceback (most recent call last):
  File "C:\Projetos\Rambo\r-crypt\r_encrypt-file.py", line 27, in <module>
    doCryptographyAction(sys.argv[1], input("Insert your key: "))
  File "C:\Projetos\Rambo\r-crypt\r_encrypt-file.py", line 19, in doCryptographyAction
    r_file.write_to_file(ciphed, new_file.file_name, new_file.extension, True)
  File "C:\Projetos\Rambo\r-crypt\r_file.py", line 48, in write_to_file
    file.write(content.encode("utf-8"))
AttributeError: 'bytes' object has no attribute 'encode'

**Comment by punishercoder** [comment]
Fixed: https://github.com/punishercoder/r_crypto/commit/ee982a6af0c21b7b6fe9ff809badca189141a3ac
